name: Deploy to EC2

on:
  push:
    branches:
      - main  # exec when pushed main branch

jobs:
  deploy:
    needs: build  # build 작업이 완료된 후 실행
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_KEY }} ec2-user@13.124.230.180 << 'EOF'
            docker pull dlwpdnr213/fastapi_test:v1
            docker stop my_fastapi_container || true
            docker rm my_fastapi_container || true
            docker run -d -p 8000:8000 --name my_fastapi_container dlwpdnr213/fastapi_test:v1
          EOF
